#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Chores.Resource", IsApplication=true)]

namespace Chores
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int gray = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int transparent = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int activityicon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int addimage = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int addnewtaskicon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int background_gray = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int backicon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_landscape = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg_portrait = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_login = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_register = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int camera_crop_height = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int camera_crop_width = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int canceltask = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int circle_yellow = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int customselector = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int groupicon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_search = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int indicator_autocrop = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int line = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int login_nor = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int login_selected = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int logomark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int msg_back = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int mytaskicon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notificationicon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int posttask = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int registerbutton_nor = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int registerbutton_selected = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int search = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int searchicon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int segmentedcontrolbutton_nor = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int segmentedcontrolbutton_selected = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tabbutton_nor = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tabbutton_selected = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int taskicon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int taskya = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int user = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060024
			public const int btnAccept = 2131099684;
			
			// aapt resource value: 0x7f060075
			public const int btnAction = 2131099765;
			
			// aapt resource value: 0x7f060037
			public const int btnAddSubPoints = 2131099703;
			
			// aapt resource value: 0x7f060064
			public const int btnCancel = 2131099748;
			
			// aapt resource value: 0x7f060056
			public const int btnClear = 2131099734;
			
			// aapt resource value: 0x7f06003a
			public const int btnCloseGroup = 2131099706;
			
			// aapt resource value: 0x7f060047
			public const int btnComplete = 2131099719;
			
			// aapt resource value: 0x7f06003d
			public const int btnCreateGroup = 2131099709;
			
			// aapt resource value: 0x7f06002d
			public const int btnJoinGroup = 2131099693;
			
			// aapt resource value: 0x7f060035
			public const int btnKick = 2131099701;
			
			// aapt resource value: 0x7f060052
			public const int btnLogin = 2131099730;
			
			// aapt resource value: 0x7f060082
			public const int btnPriorityHigh = 2131099778;
			
			// aapt resource value: 0x7f060080
			public const int btnPriorityLow = 2131099776;
			
			// aapt resource value: 0x7f060081
			public const int btnPriorityMedium = 2131099777;
			
			// aapt resource value: 0x7f060063
			public const int btnRegister = 2131099747;
			
			// aapt resource value: 0x7f060088
			public const int btnSelectDate = 2131099784;
			
			// aapt resource value: 0x7f060085
			public const int btnSelectTime = 2131099781;
			
			// aapt resource value: 0x7f060042
			public const int btnSendJoin = 2131099714;
			
			// aapt resource value: 0x7f060053
			public const int btnSignup = 2131099731;
			
			// aapt resource value: 0x7f06002a
			public const int discard = 2131099690;
			
			// aapt resource value: 0x7f060028
			public const int image = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int imageView1 = 2131099686;
			
			// aapt resource value: 0x7f060033
			public const int imageView2 = 2131099699;
			
			// aapt resource value: 0x7f060065
			public const int imgAddNewTask = 2131099749;
			
			// aapt resource value: 0x7f060022
			public const int imgBack = 2131099682;
			
			// aapt resource value: 0x7f060012
			public const int imgBtnActivity = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int imgBtnGroup = 2131099672;
			
			// aapt resource value: 0x7f06000f
			public const int imgBtnHome = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int imgBtnNotify = 2131099675;
			
			// aapt resource value: 0x7f060015
			public const int imgBtnTask = 2131099669;
			
			// aapt resource value: 0x7f060076
			public const int imgCancel = 2131099766;
			
			// aapt resource value: 0x7f06004a
			public const int imgMark = 2131099722;
			
			// aapt resource value: 0x7f06005d
			public const int imgPhoto = 2131099741;
			
			// aapt resource value: 0x7f060077
			public const int imgPost = 2131099767;
			
			// aapt resource value: 0x7f06003f
			public const int imgSearch = 2131099711;
			
			// aapt resource value: 0x7f06004f
			public const int imgSeperator = 2131099727;
			
			// aapt resource value: 0x7f060044
			public const int imgUser = 2131099716;
			
			// aapt resource value: 0x7f060031
			public const int imgUserPhoto = 2131099697;
			
			// aapt resource value: 0x7f060045
			public const int lblName = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int lblPoints = 2131099718;
			
			// aapt resource value: 0x7f060011
			public const int linearBtnActivity = 2131099665;
			
			// aapt resource value: 0x7f060017
			public const int linearBtnGroup = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int linearBtnHome = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int linearBtnNotify = 2131099674;
			
			// aapt resource value: 0x7f060014
			public const int linearBtnTask = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int linearButtons = 2131099661;
			
			// aapt resource value: 0x7f060043
			public const int linearCaption = 2131099715;
			
			// aapt resource value: 0x7f060060
			public const int linearEmail = 2131099744;
			
			// aapt resource value: 0x7f06001e
			public const int linearFirstline = 2131099678;
			
			// aapt resource value: 0x7f060007
			public const int linearGroup = 2131099655;
			
			// aapt resource value: 0x7f060039
			public const int linearGroupActions = 2131099705;
			
			// aapt resource value: 0x7f06002e
			public const int linearGroupMembers = 2131099694;
			
			// aapt resource value: 0x7f06003b
			public const int linearGroupRoot = 2131099707;
			
			// aapt resource value: 0x7f060058
			public const int linearItem = 2131099736;
			
			// aapt resource value: 0x7f06006f
			public const int linearLayout1 = 2131099759;
			
			// aapt resource value: 0x7f060030
			public const int linearLayout2 = 2131099696;
			
			// aapt resource value: 0x7f060032
			public const int linearLayout3 = 2131099698;
			
			// aapt resource value: 0x7f060034
			public const int linearLayout4 = 2131099700;
			
			// aapt resource value: 0x7f060036
			public const int linearLayout5 = 2131099702;
			
			// aapt resource value: 0x7f060054
			public const int linearMemberRoot = 2131099732;
			
			// aapt resource value: 0x7f06004d
			public const int linearName = 2131099725;
			
			// aapt resource value: 0x7f06007a
			public const int linearNames = 2131099770;
			
			// aapt resource value: 0x7f060050
			public const int linearPassword = 2131099728;
			
			// aapt resource value: 0x7f060068
			public const int linearPerson = 2131099752;
			
			// aapt resource value: 0x7f06005b
			public const int linearPhoto = 2131099739;
			
			// aapt resource value: 0x7f060023
			public const int linearPostCancel = 2131099683;
			
			// aapt resource value: 0x7f06007f
			public const int linearPriority = 2131099775;
			
			// aapt resource value: 0x7f06003e
			public const int linearSearch = 2131099710;
			
			// aapt resource value: 0x7f06008a
			public const int linearSecondline = 2131099786;
			
			// aapt resource value: 0x7f06005f
			public const int linearSeperator = 2131099743;
			
			// aapt resource value: 0x7f060003
			public const int linearSubTitle = 2131099651;
			
			// aapt resource value: 0x7f060087
			public const int linearTaskDate = 2131099783;
			
			// aapt resource value: 0x7f06007e
			public const int linearTaskMain = 2131099774;
			
			// aapt resource value: 0x7f060084
			public const int linearTaskTime = 2131099780;
			
			// aapt resource value: 0x7f06007c
			public const int linearTasks = 2131099772;
			
			// aapt resource value: 0x7f060000
			public const int linearTitle = 2131099648;
			
			// aapt resource value: 0x7f060074
			public const int listBidUsers = 2131099764;
			
			// aapt resource value: 0x7f06000c
			public const int listDetailTasks = 2131099660;
			
			// aapt resource value: 0x7f06002f
			public const int listGroupMembers = 2131099695;
			
			// aapt resource value: 0x7f060041
			public const int listGroups = 2131099713;
			
			// aapt resource value: 0x7f060057
			public const int listNotifications = 2131099735;
			
			// aapt resource value: 0x7f06000a
			public const int listTasks = 2131099658;
			
			// aapt resource value: 0x7f06001d
			public const int relativeItemRoot = 2131099677;
			
			// aapt resource value: 0x7f060025
			public const int relativeLayout1 = 2131099685;
			
			// aapt resource value: 0x7f06005c
			public const int rlImagePhoto = 2131099740;
			
			// aapt resource value: 0x7f06002b
			public const int rotateLeft = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int rotateRight = 2131099692;
			
			// aapt resource value: 0x7f060029
			public const int save = 2131099689;
			
			// aapt resource value: 0x7f060004
			public const int space1 = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int space2 = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int space3 = 2131099654;
			
			// aapt resource value: 0x7f06004c
			public const int spaceImage = 2131099724;
			
			// aapt resource value: 0x7f060049
			public const int spaceTop = 2131099721;
			
			// aapt resource value: 0x7f060009
			public const int spinGroup = 2131099657;
			
			// aapt resource value: 0x7f060078
			public const int spinnerGroup = 2131099768;
			
			// aapt resource value: 0x7f060079
			public const int spinnerUser = 2131099769;
			
			// aapt resource value: 0x7f06000b
			public const int txtActivityTitle = 2131099659;
			
			// aapt resource value: 0x7f06005e
			public const int txtAddImage = 2131099742;
			
			// aapt resource value: 0x7f060013
			public const int txtBtnActivity = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int txtBtnGroup = 2131099673;
			
			// aapt resource value: 0x7f060010
			public const int txtBtnHome = 2131099664;
			
			// aapt resource value: 0x7f06001c
			public const int txtBtnNotify = 2131099676;
			
			// aapt resource value: 0x7f060016
			public const int txtBtnTask = 2131099670;
			
			// aapt resource value: 0x7f060062
			public const int txtConfirmPassword = 2131099746;
			
			// aapt resource value: 0x7f06005a
			public const int txtDate = 2131099738;
			
			// aapt resource value: 0x7f06008b
			public const int txtDescription = 2131099787;
			
			// aapt resource value: 0x7f060061
			public const int txtEmail = 2131099745;
			
			// aapt resource value: 0x7f060073
			public const int txtFinishDate = 2131099763;
			
			// aapt resource value: 0x7f060072
			public const int txtFinishDateLabel = 2131099762;
			
			// aapt resource value: 0x7f060008
			public const int txtGroup = 2131099656;
			
			// aapt resource value: 0x7f06006b
			public const int txtGroupLabel = 2131099755;
			
			// aapt resource value: 0x7f06003c
			public const int txtGroupName = 2131099708;
			
			// aapt resource value: 0x7f060089
			public const int txtJobDate = 2131099785;
			
			// aapt resource value: 0x7f06007d
			public const int txtJobDescription = 2131099773;
			
			// aapt resource value: 0x7f06007b
			public const int txtJobName = 2131099771;
			
			// aapt resource value: 0x7f060083
			public const int txtJobPoint = 2131099779;
			
			// aapt resource value: 0x7f060086
			public const int txtJobTime = 2131099782;
			
			// aapt resource value: 0x7f060055
			public const int txtMemberName = 2131099733;
			
			// aapt resource value: 0x7f060059
			public const int txtMessage = 2131099737;
			
			// aapt resource value: 0x7f06004e
			public const int txtName = 2131099726;
			
			// aapt resource value: 0x7f060038
			public const int txtNewPoints = 2131099704;
			
			// aapt resource value: 0x7f060002
			public const int txtPageTitle = 2131099650;
			
			// aapt resource value: 0x7f060051
			public const int txtPassword = 2131099729;
			
			// aapt resource value: 0x7f060027
			public const int txtPoints = 2131099687;
			
			// aapt resource value: 0x7f060071
			public const int txtPostDate = 2131099761;
			
			// aapt resource value: 0x7f060070
			public const int txtPostDateLabel = 2131099760;
			
			// aapt resource value: 0x7f06006e
			public const int txtPriority = 2131099758;
			
			// aapt resource value: 0x7f06006d
			public const int txtPriorityLabel = 2131099757;
			
			// aapt resource value: 0x7f060040
			public const int txtSearchName = 2131099712;
			
			// aapt resource value: 0x7f060020
			public const int txtState = 2131099680;
			
			// aapt resource value: 0x7f060048
			public const int txtStatus = 2131099720;
			
			// aapt resource value: 0x7f060069
			public const int txtTaskDescLabel = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int txtTaskDescription = 2131099754;
			
			// aapt resource value: 0x7f060066
			public const int txtTaskLabel = 2131099750;
			
			// aapt resource value: 0x7f060021
			public const int txtTaskName = 2131099681;
			
			// aapt resource value: 0x7f060067
			public const int txtTaskStatus = 2131099751;
			
			// aapt resource value: 0x7f060005
			public const int txtTaskTitle = 2131099653;
			
			// aapt resource value: 0x7f06004b
			public const int txtTitle = 2131099723;
			
			// aapt resource value: 0x7f06006c
			public const int txtUserLabel = 2131099756;
			
			// aapt resource value: 0x7f06001f
			public const int txtUserName = 2131099679;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActivityItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Chores = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChoresItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int cropimage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Group = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int GroupListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int GroupNew = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Home = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int HomeListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Login = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MemberCustomView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Notification = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int NotificationItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Signup = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SpinnerText = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Task = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int TaskBidUserItem = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int TaskDetail = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int TaskNew = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int TaskNewListItem = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_title = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int msg_register_success = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int msg_server_error = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int msg_wait = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
